In [1]:
import numpy as np    # "np" is just the standard nickname

speeds_list = [0, 12, 25, 41]
print(speeds_list * 2)
# [0, 12, 25, 41, 0, 12, 25, 41]   <- list repeated, NOT doubled!

speeds = np.array([0, 12, 25, 41])
print(speeds * 2)
# [ 0 24 50 82]                    <- every number doubled

[0, 12, 25, 41, 0, 12, 25, 41]
[ 0 24 50 82]


In [3]:
import numpy as np

image = np.zeros((480, 640, 3))

print(image.shape)# (480, 640, 3)
print(image.ndim)
print(image[0, 0])           # [0. 0. 0.] -> the top-left pixel: its R, G, B values

image[0, 0] = [255, 0, 0]    # make the top-left pixel pure red
print(image[0, 0])           # [255.   0.   0.]

(480, 640, 3)
3
[0. 0. 0.]
[255.   0.   0.]


In [9]:
temps = np.array([85, 90, 102, 95, 110, 78])
print(temps.shape)
print(temps.dtype)

temps_F = temps * (9/5) + 32
time = np.arange(0, 60, 10)
print(time.shape)
print(temps.reshape(6,1).shape)

(6,)
int64
(6,)
(6, 1)


**Part A: Explain in your own words (short answers)**
Give two reasons a NumPy array is faster and more convenient than a Python list for math.
What is the difference between shape (4,) and shape (1, 4)?
In ML data (like your decision tree's training data), what do the rows and what do the columns usually represent?


**Part B: Predict the output (don't run it first)**
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
**What do these print?**
   print(a * 2)
   print(a + b)
   print(a > 1)
   print([1, 2] * 2)
**What is x.dtype here, and why?**
   x = np.array([1, 2, 3.5])
   
**What do m.shape, m.ndim and m.size give?**
   m = np.array([[1, 2, 3],
                 [4, 5, 6]])
**A color image is 100 pixels tall and 200 pixels wide. What is its shape, and what does each number mean?**


**Part C: Small coding exercise (in your notebook)**

Pretend these are engine temperature readings (°C), one every 10 seconds:

temps = np.array([85, 90, 102, 95, 110, 78])


**Print the shape and dtype.
Convert all values to Fahrenheit (C * 9/5 + 32) without a loop.
Create a matching time array [0, 10, 20, 30, 40, 50] using np.arange, and confirm its shape equals the shape of temps.
Reshape temps into a column (6 rows, 1 column) and print the new shape.**

Give two reasons a NumPy array is faster and more convenient than a Python list for math. ->  **it is faster because 1. it uses C and array offers mathematical operations**
What is the difference between shape (4,) and shape (1, 4)? **former is a 1D array and later is 2D (1 row, 4 column)**
In ML data (like your decision tree's training data), what do the rows and what do the columns usually represent? **rows represent sample and column represent Feature**
a*2 = 2,4,6 ..... a+b = 5,7,9 ..... a>1 = false, true, true .... 1,2,1,2
float
shape (2,3), 2D, 6
(100, 200, 3) -- 100px height and 200px width with 3 channels (RGB)
C: 
temps = np.array([85, 90, 102, 95, 110, 78])
print(temps.shape)
print(temps.dtype)

temps_F = temps * (9/5) + 32
time = np.arange(0, 60, 10)
print(time.shape)
print(temps.reshape(6,1).shape)

In [ ]:
speed = np.array([0, 12, 25, 41, 55, 58, 57, 40, 22, 0])

# Columns: time (s), speed (km/h), steering angle (deg)
log = np.array([[0,  0,  0.0],
                [1, 12,  1.5],
                [2, 25,  3.0],
                [3, 41, -2.0]])          # shape (4, 3)

print(log[1, 2])       # 1.5          row 1, column 2
print(log[1])          # [ 1.  12.   1.5]   the whole row 1 (one sample)
print(log[-1])         # [ 3.  41.  -2. ]   the last row
print(log[:, 1])       # [ 0. 12. 25. 41.]  ALL rows, column 1 (the speed column)
print(log[1:3, 1:])    # rows 1-2, columns 1 to the end
                       # [[12.   1.5]
                       #  [25.   3. ]]

fast_rows = log[log[:, 1] > 20]
print(fast_rows)
# [[ 2.  25.   3.]
#  [ 3.  41.  -2.]]

In [56]:
data = np.array([[0, 3.9, 25],
                 [1, 3.8, 27],
                 [2, 3.4, 31],
                 [3, 3.7, 29],
                 [4, 3.2, 35],
                 [5, 3.6, 30]])

voltage = data[:, 1]
print(voltage)
temp = data[:, 2]
print(temp)

print((data[:, 1] < 3.5).sum())
print((data[:, 1] < 3.5).mean())
print(data[(data[:, 1] < 3.5) & (data[:, 2] > 30)])
print(data[(data[:, 1] < 3.5) & (data[:, 2] > 30)][:,0])
print(np.where((data[:, 1] < 3.5), 1, 0))
capped = temp.copy()
capped[capped > 33] = 33
print(capped)
print(data[:, 2])

[3.9 3.8 3.4 3.7 3.2 3.6]
[25. 27. 31. 29. 35. 30.]
2
0.3333333333333333
[[ 2.   3.4 31. ]
 [ 4.   3.2 35. ]]
[2. 4.]
[0 0 1 0 1 0]
[25. 27. 31. 29. 33. 30.]
[25. 27. 31. 29. 35. 30.]
